version: '3'

services:

  mysql-5.7:
    image: mysql:5.7
    container_name: mysql-5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: puit
      MYSQL_USER: admin
      MYSQL_PASSWORD: 4444
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql_puit:/var/lib/mysql
    networks:
      - mysql_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - mysql-5.7
    environment:
      PMA_HOST: mysql-5.7
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: 4444
      PMA_DATABASE: puit
    restart: always
    ports:
      - "8080:80"
    volumes:
      - mysql_puit:/var/lib/mysql
    networks:
      - mysql_network
    
volumes:
  mysql_puit:

networks:
  mysql_network:
    driver: bridge
